#!/usr/bin/env python3
"""Launch the lightweight local web UI for hybrid-parameter exploration.

This module is the human-facing entrypoint for the research UI added under
``bubbly_flows/tests/ui/``. It is intentionally thin: the real behavior lives in
``bubbly_flows.tests.ui.server``, while this file only handles import bootstrapping,
CLI parsing, and delegation to :func:`serve`.

API overview for agents reading this entrypoint:
- ``main()`` parses ``--host`` and ``--port`` and then calls
  ``bubbly_flows.tests.ui.server.serve(host=..., port=...)``.
- ``serve()`` owns the HTTP server, debounce loop, and background rerun logic.
- The server exposes a small JSON/image API used by the single-page UI:
  - ``GET /``: HTML shell from ``ui/static/index.html``
  - ``GET /api/state``: current params, run status, summary, and cache-busted image URLs
  - ``POST /api/params``: partial parameter update; schedules a debounced rerun
  - ``POST /api/reset``: restore ``baseline_hybrid_original`` parameters
  - ``GET /api/image/gold``: fixed gold-reference overlay for ``img006001``
  - ``GET /api/image/current``: latest hybrid overlay generated by the backend runner

Execution model:
- The page is fixed to a single source image, currently
  ``ZeroG_FlightDay_Test_C1S0014_img006001``.
- Parameter edits do not write permanent experiment outputs; the UI keeps only the
  latest temporary render under ``bubbly_flows/tests/output/ui/``.
- Reruns are debounced for 5 seconds after the last parameter change.
- Hybrid inference is performed by the UI server layer, not by this launcher.

Use this file when you need to start or reason about the UI as an application. Use
``bubbly_flows.tests.ui.server`` when you need endpoint or orchestration details.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in {None, ""}:
    repo_root = Path(__file__).resolve().parents[2]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

from bubbly_flows.tests.ui.server import serve


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the local hybrid tuning UI.")
    parser.add_argument("--host", default="127.0.0.1", help="Bind host. Keep 127.0.0.1 for SSH tunneling.")
    parser.add_argument("--port", default=7860, type=int, help="Bind port.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(f"Hybrid UI listening on http://{args.host}:{args.port}")
    serve(host=args.host, port=args.port)


if __name__ == "__main__":
    main()
